name: Issue Greeting

on:
  issues:
    types:
      - opened

jobs:
  greet-issue-author:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Send Greeting Message
      run: |
        ISSUE_USER=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}" \
          | jq -r '.user.login')

        GREETING_MESSAGE="Hello, @$ISSUE_USER! Thank you for opening this issue. We appreciate your feedback. Our team will review it as soon as possible."

        curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"body\":\"$GREETING_MESSAGE\"}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
