name: issue-greeting

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "Hello, Thank you for opening this issue. We appreciate your contribution. Our team will review it as soon as possible."
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}