name: Issue Greeting and Comment

on:
  issues:
    types:
      - opened

jobs:
  greet-and-comment:
    runs-on: ubuntu-latest

  permissions:
    issues: write

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Send Greeting Message
      run: |
        ISSUE_USER=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}" \
          | jq -r '.user.login')

        GREETING_MESSAGE="Hello, @$ISSUE_USER! Thank you for opening this issue. We appreciate your contribution."

        curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"body\":\"$GREETING_MESSAGE\"}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"

    - name: Comment on the Issue
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        COMMENT_MESSAGE="We will look into this issue and provide assistance shortly. Thank you for reporting!"

        curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"body\":\"$COMMENT_MESSAGE\"}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments"
